# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 139399a60c16ade29ea6ec0f414f1d9984388319255d0b43cd3ce23b1a1264190de50fb4a54d537910439ce2ce0b1e83aa19bed0182b5e43a12047627115ea50

test:
  secret_key_base: 9cd538e3d31bfc36df27d3530f69f61797e697295e0c2f06ffe1d06792edc4ca19196f8875bb6e079ae5556e846f218f2570f244025cf4f2b96e8b3e4ac95716

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
